Отображает фото пользователей - дз7
htmlacademy-javascript/2156249-kekstagram-1 pull request #5
Opened 2024-02-16 08:23 UTC by DariaEgarmina

2024-02-16 09:34 UTC, wonderjs requested changes

2024-02-16 09:34 UTC, wonderjs commented on js/picture.js
> +userPhotos.forEach((photo) => {
1️⃣ 
Старайся думать "функциями", отрисовать список картинок нам может понадобиться несколько раз. Давай сделаем функцию `renderPhotos`, которая будет принимать массив фотографии и отрисовывать их. Дополнительно можно вынести функцию createPhotoElement/getPhotoElement, которая будет клонировать темплейт, заполнять данный и возвращать из функции. 
```
const createPhotoElement = (photo) => {
  const pictureElement = pictureTemplate.cloneNode(true);
  ...
  return photoElement;
};

const renderPhotos = (photos) => {
  const fragment = document.createDocumentFragment();
  photos.forEach((photo) => {
    const photoElement = createPhotoElement(photo);
    fragment.appendChild(photoElement);
  });
  picturesSection.appendChild(fragment);
};
```
Функцию `renderPhotos` экспортируем из модуля и используем в нашей точке входа, модуле main.js

2024-02-16 09:34 UTC, wonderjs commented on js/picture.js
> +const userPhotos = createPhotos();
Мы уже создали фото в модуле main.js, давай там запишем их в переменную и передадим в функцию renderPhotos, которая уже будет рисовать комментарии.

2024-02-16 09:34 UTC, wonderjs commented on js/picture.js
> +const picturesSectionFragment = document.createDocumentFragment();
можно просто `fragment`

2024-02-16 09:34 UTC, wonderjs commented on js/picture.js
> +const picturesSection = document.querySelector('.pictures');
Давай в рамках нашего проекта для всех DOM-элементов использовать постфикс `Element`, тогда ты всегда будешь знать что переменная photo - это данные, а photoElement - это какой-то элемент разметки. 
DOM-переменные можно называть не по классу, который они содержат, а просто по смыслу. Иногда классы бывают оч длинные и неудобные или по ним нельзя понять а что это такое. 
Здесь можно использовать вариант `containerElement`

2024-02-16 09:34 UTC, wonderjs commented on js/main.js
>  console.log(
Давай уберем отсюда лог и запишем результат вызова `createPhotos` в переменную `userPhotos` (или просто `photos`). 
Потом вызовем функцию рендера картинок и передадим туда этот массив.

2024-02-16 09:35 UTC, wonderjs commented on js/picture.js
> +  pictureElement.querySelector('.picture__comments').textContent = photo.comments.message;
здесь нам нужно указать число комментариев, те длину массива comments
Сейчас тебя такое =) 
![Снимок экрана 2024-02-16 в 10 19 44](https://github.com/htmlacademy-javascript/2156249-kekstagram-1/assets/25072556/1d07e2f0-2fde-4e9a-92bf-7411583b6c41)

2024-02-19 12:07 UTC, wonderjs commented on js/picture.js
> +import {createPhotos} from './data.js';
Теперь здесь этот импорт не нужен, те не используется, убираем)

2024-02-19 12:11 UTC, wonderjs requested changes

2024-02-19 12:11 UTC, wonderjs commented on js/picture.js
> +  photoElement.querySelector('.picture__comments').textContent = photo.comments.message;
нам нужна количество комментариев, те длина массива, так что photo.comments.length

2024-02-19 12:51 UTC, DariaEgarmina commented on js/picture.js
> +import {createPhotos} from './data.js';
опять невнимательность

2024-02-19 12:56 UTC, merged