Открывается и закрывается
htmlacademy-javascript/2156249-kekstagram-1 pull request #6
Opened 2024-02-25 16:12 UTC by DariaEgarmina

2024-02-25 18:57 UTC, wonderjs requested changes

2024-02-25 18:57 UTC, wonderjs commented on js/data.js
> +  dataset: `picture${ id }`,
Избыточно, у нас уже есть id у фото, просто используй его

2024-02-25 18:57 UTC, wonderjs commented on js/render-photos.js
> +  photoElement.dataset.pictureNumber = photo.dataset;
`id` всё таки более общепринято. Лучше: 
`photoElement.dataset.id = photo.id;`
либо 
`photoElement.dataset.pictureId = photo.id;`

2024-02-25 18:57 UTC, wonderjs commented on js/big-picture.js
> +const bigPictureHandler = function (array) {
Ох какая длинная колбаса =) Разбивай на мелкие функции и выноси их из bigPictureHandler
1) Рендер комментариев (можно завести темплейт в index.html как для картинок маленьких, чтобы упростить их рендер и заполнение данными)
2) Рендер большой картинки (заполнение данных и вызов рендера комментариев)
3) Открытие большой картинки (добавление классов на body, скрытие элементов, вызов рендера большой картинки. Навешивание обработчика на закрытие по esc
4) Обработчик на крестик можно повесить один раз и не убирать, просто выносим 
5) Функция закрытия модалки (удаление классов, обработчика на esc)
Внутри обработичка bigPictureHandler остается только определение элемента по которому кликнули и вызов функции открытия большой картинки

2024-02-25 18:57 UTC, wonderjs commented on js/big-picture.js
> +    const bigPictureImg = bigPictureElement.querySelector('img');
Все селекторы, касающиеся bigPictureElement смело выноси наружу, наверх модуля, нам не нужно их искать каждый раз

2024-02-25 18:57 UTC, wonderjs commented on js/big-picture.js
> +    const targetLink = evt.target.closest('a');
Лучше искать по классу .picture

2024-03-01 16:53 UTC, wonderjs requested changes
Сейчас у тебя получился довольно большой модуль big-picture, предлагаю разбить на несколько мелких: 
`comments.js` функции:
- создание одного комментария, 
- рендер всех комментариев 
- очистка контейнера с комментарими

Экспортируем функции рендера и очистки комментариев
`gallery.js: ` 

Функция навешивания обработчика на контейнер, экспортируем ее и используем в main.js
`big-picture.js`:
Всё остальное, экспортируем функцию открытия большой картинки

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +const picturesContainer = document.querySelector('.pictures');
Чтобы было легче ориентироваться где переменные с DOM-элементами, а где с данными, в рамках проекта можем для всех DOM-елементов использовать постфикс `Element`. Думаю тогда тебе будет легче придумывать имена переменным. 
`picturesContainer` -> `containerElement`

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +const bigPictureImg = bigPictureElement.querySelector('img');
`bigPictureImg` -> `imgElement`

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +const commentsCount = bigPictureElement.querySelector('.comments-count');
`likesCount` -> `likesCountElement`
`commentsCount` -> `commentsCountElement`
и тп

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +const fragment = document.createDocumentFragment();
Фрагмент переносим в функцию рендера комментариев

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +const closeElement = document.querySelector('.big-picture__cancel');
более понятно будет `closeButtonElement`

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +const createCommentElement = (commentsArrayElement) => {
Лучше `getCommentElement` (тк мы возвращаем элемент комментария из функции)
слово "array" старайся не использовать вообще, называем более осознанно параметры. Либо `comment` или можно использовать деструктуризацию `{ avatar, name, message }`

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +  commentElement.querySelector('.social__picture').alt = commentsArrayElement.name;
Два раза ищем один элемент `commentElement.querySelector('.social__picture')`, лучше сохранить в переменную строчкой выше

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +const createBigPicture = (requiredThumbnail) => {
Эту функцию можно назвать `renderBigPicture`, параметр либо `photo`/`picture` (thumbnail это миниатура, а тут у нас объект с данными по фото) , либо сразу деструктурируем `{comments, description, likes, url }`

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +  commentsContainer.innerHTML = '';
вот это выносим в функцию `removeComments`

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +  commentsArray.forEach((commentsArrayElement) => {
А всё что касается рендера комментариев выносим в отдельную функцию `renderComments`
```
const renderComments = (comments) => {
  const fragment = document.createDocumentFragment();
  comments.forEach((commentsArrayElement) => {
    const commentElement = getCommentElement(commentsArrayElement);
    fragment.append(commentElement);
  });
  containerElement.append(fragment);
};
```
Здесь будет просто ее вызов с передачей массива комментариев

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +const openBigPicture = (requiredThumbnail, array) => {
Параметр здесь нужен только один, данные по конкретной фотографии, называем `photo` или `picture`

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +  createBigPicture(requiredThumbnail, array);
Тут лишний второй параметр, он не нужен в функции createBigPicture

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +  document.addEventListener('keydown', (evt) => {
Выносим всю эту радость в отдельную функцию (называем как обработчик) в самом конце модуля, определяем ее через function, тк нам нужен хостинг (всплытие):
```
function onDocumentKeydown(evt) {
  if (isEscapeKey(evt)) {
    evt.preventDefault();
    closeBigPicture();
  }
}
```

Выше определяем функцию закрытия большой кратинки:
```
const closeBigPicture = () => {
  pictureElement.classList.add('hidden');
  document.body.classList.remove('modal-open');

  document.removeEventListener('keydown', onDocumentKeydown);
};
```
Внутри openBigPicture остается только навешивание обработчика:
```
document.addEventListener('keydown', onDocumentKeydown);
```

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +  document.body.classList.remove('modal-open');
Тут внутренности заменяем на вызов функции закрытия большой картинки

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +const bigPictureHandler = (array) => {
Вот эту функцию давай вынесем в отдельный модуль `gallery.js`. Я бы переименовала в setGalleryListener, чтобы было максимально понятно что она делает.

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +    const targetLink = evt.target.closest('.picture');
Я бы назвала pictureElement

2024-03-01 16:53 UTC, wonderjs commented on js/big-picture.js
> +    const targetLinkId = targetLink.getAttribute('data-picture-id');
У нас возможна ситуация, когда пользователь кликнет не точно по картинке, а между ними, так что нужно обработать кейс, когда элемента targetLink (pictureElement) не будет, так что отсюда всё заворачиваем в условие проверки существования этой переменной:
```
    if (pictureElement) {
      const pictureId = pictureElement.getAttribute('data-picture-id');

      //ищет в данных объект с таким же датасетом
      const photo = photos.find((arrayElement) => arrayElement.id === +pictureId);

      // открывает и закрывает большую картинку
      openBigPicture(photo);
    }
```
написала с примером более понятным названий переменных

2024-03-04 10:07 UTC, DariaEgarmina commented on js/big-picture.js
> +const picturesContainer = document.querySelector('.pictures');
назвала galleryContainerElement, чтобы было уточнение контейнер для чего

2024-03-04 14:38 UTC, merged